/// 12개 언어 문자열 표. 키는 [S]의 getter 이름과 같다.
///
/// 빠진 키는 영어로 대체되므로(=[S]._ 참조), 새 문자열을 추가할 땐
/// ko·en 두 곳만 채워도 앱은 돌아간다. 나머지는 채워 넣으면 된다.
library;

const kLangCodes = [
  'ko', 'en', 'ja', 'zh', 'es', 'fr', //
  'de', 'pt', 'ru', 'th', 'vi', 'id', //
];

/// 언어 선택 화면에 뜨는 이름 — 각 언어를 그 언어로 적는다.
const kLangNames = {
  'ko': '한국어',
  'en': 'English',
  'ja': '日本語',
  'zh': '中文',
  'es': 'Español',
  'fr': 'Français',
  'de': 'Deutsch',
  'pt': 'Português',
  'ru': 'Русский',
  'th': 'ไทย',
  'vi': 'Tiếng Việt',
  'id': 'Bahasa Indonesia',
};

const kStrings = <String, Map<String, String>>{
  'ko': {
    'appTitle': '삐약푸쉬',
    'start': '시작',
    'daily': '데일리',
    'stickerBook': '스티커북',
    'decoBoard': '꾸미기',
    'settings': '설정',
    'chapterTitle': '챕터',
    'lockedChapter': '이전 챕터를 8판 깨면 열려요',
    'needMoreClears': '이 챕터에서 {n}개만 더 깨면 다음 챕터가 열려요',
    'moves': '이동',
    'optimal': '최적',
    'undo': '되돌리기',
    'restart': '다시',
    'hint': '힌트',
    'next': '다음',
    'list': '목록',
    'clear': '클리어!',
    'nextChapter': '다음 챕터',
    'chapterCleared': '챕터 클리어!',
    'allCleared': '모든 챕터 클리어! 대단해요!',
    'toTitle': '처음으로',
    'challenge': '도전',
    'tutorial1': '화면을 누른 채 기울여서 삐약이를 움직여요!',
    'tutorial1Dpad': '방향 버튼을 눌러서 삐약이를 움직여요!',
    'tutorial2': '알을 밀어서 둥지에 쏙! 넣어주세요',
    'tutorial3': '실수했다면 되돌리기를 눌러요',
    'deadlockHint': '알이 구석에 끼었어요… 되돌리기를 눌러볼까?',
    'noHint': '지금은 길이 없어요… 되돌리기!',
    'soundOn': '소리',
    'joystickHint': '아무 데나 누르고 기울여 보세요',
    'controlScheme': '조작 방식',
    'unlockAll': '모든 챕터 열기 (확인용)',
    'ctlJoystick': '조이스틱 — 아무 데나 눌러서 기울이기',
    'ctlDpad': '방향키 — 십자 버튼 누르기',
    'resetAll': '진행 기록 지우기',
    'resetConfirm': '정말 모든 기록을 지울까요?',
    'cancel': '취소',
    'ok': '확인',
    'language': '언어',
    'languageSystem': '기기 언어 따르기',
    'dailyTitle': '오늘의 퍼즐',
    'dailyPlay': '도전!',
    'dailyDone': '오늘 퍼즐 완료!',
    'streak': '연속 출석',
    'day': '일',
    'stickerLocked': '별을 모으면 열려요',
    'stickerCount': '개',
    'hintsLeft': '남은 힌트',
    'hintEmpty': '힌트를 다 썼어요',
    'hintHowTo': '새 스테이지를 깨면 힌트를 1개 받아요.\n오늘의 퍼즐을 깨면 2개를 받아요.',
    'hintGot': '힌트 +{n}',
    'ch1': '풀밭', 'ch2': '얼음길', 'ch3': '비밀 굴', 'ch4': '단추와 문',
    'ch5': '금 간 바닥', 'ch6': '얼음 굴', 'ch7': '미끄럼 자물쇠',
    'ch8': '부서지는 얼음', 'ch9': '굴과 자물쇠', 'ch10': '무너지는 통로',
    'ch11': '넓은 들판', 'ch12': '알 넷의 방', 'ch13': '얼어붙은 광장',
    'ch14': '굴 미로', 'ch15': '잠긴 정원', 'ch16': '뒤엉킨 길',
    'ch17': '삐약의 시험', 'ch18': '다섯 알의 탑', 'ch19': '마지막 관문',
    'ch20': '삐약 마스터',
    'act1': '1막 · 배우기', 'act2': '2막 · 뒤섞기',
    'act3': '3막 · 넓어지기', 'act4': '4막 · 시험',
  },
  'en': {
    'appTitle': 'Peep Push',
    'start': 'Play',
    'daily': 'Daily',
    'stickerBook': 'Stickers',
    'decoBoard': 'Decorate',
    'settings': 'Settings',
    'chapterTitle': 'Chapter',
    'lockedChapter': 'Clear 8 stages in the previous chapter to unlock',
    'needMoreClears': 'Clear {n} more in this chapter to open the next one',
    'moves': 'Moves',
    'optimal': 'Best',
    'undo': 'Undo',
    'restart': 'Retry',
    'hint': 'Hint',
    'next': 'Next',
    'list': 'Stages',
    'clear': 'Cleared!',
    'nextChapter': 'Next chapter',
    'chapterCleared': 'Chapter cleared!',
    'allCleared': 'All chapters cleared! Amazing!',
    'toTitle': 'Home',
    'challenge': 'Challenge',
    'tutorial1': 'Hold anywhere and tilt to move the chick!',
    'tutorial1Dpad': 'Press the arrow buttons to move the chick!',
    'tutorial2': 'Push the eggs into the nests!',
    'tutorial3': 'Made a mistake? Tap undo',
    'deadlockHint': 'The egg is stuck in a corner… try undo?',
    'noHint': 'No way through right now… undo!',
    'soundOn': 'Sound',
    'joystickHint': 'Touch anywhere and tilt',
    'controlScheme': 'Controls',
    'unlockAll': 'Unlock all chapters (for testing)',
    'ctlJoystick': 'Joystick — touch anywhere and tilt',
    'ctlDpad': 'Arrows — tap the D-pad',
    'resetAll': 'Erase all progress',
    'resetConfirm': 'Erase all progress for real?',
    'cancel': 'Cancel',
    'ok': 'OK',
    'language': 'Language',
    'languageSystem': 'Follow device language',
    'dailyTitle': "Today's puzzle",
    'dailyPlay': 'Play!',
    'dailyDone': "Today's puzzle done!",
    'streak': 'Streak',
    'day': 'd',
    'stickerLocked': 'Collect stars to unlock',
    'stickerCount': '',
    'hintsLeft': 'Hints left',
    'hintEmpty': 'You are out of hints',
    'hintHowTo': 'Clear a new stage to get 1 hint.\nClear the daily puzzle for 2.',
    'hintGot': 'Hint +{n}',
    'ch1': 'Meadow', 'ch2': 'Ice Path', 'ch3': 'Secret Burrow',
    'ch4': 'Buttons and Doors', 'ch5': 'Cracked Floor', 'ch6': 'Ice Burrow',
    'ch7': 'Slippery Lock', 'ch8': 'Breaking Ice', 'ch9': 'Burrow and Lock',
    'ch10': 'Crumbling Path', 'ch11': 'Wide Field', 'ch12': 'Room of Four Eggs',
    'ch13': 'Frozen Plaza', 'ch14': 'Burrow Maze', 'ch15': 'Locked Garden',
    'ch16': 'Tangled Paths', 'ch17': "Chick's Trial", 'ch18': 'Tower of Five Eggs',
    'ch19': 'Final Gate', 'ch20': 'Peep Master',
    'act1': 'Act 1 · Learn', 'act2': 'Act 2 · Mix',
    'act3': 'Act 3 · Expand', 'act4': 'Act 4 · Trial',
  },
  'ja': {
    'appTitle': 'ピヨプッシュ',
    'start': 'あそぶ',
    'daily': 'デイリー',
    'stickerBook': 'シール',
    'decoBoard': 'かざる',
    'settings': '設定',
    'chapterTitle': 'チャプター',
    'lockedChapter': '前のチャプターを8ステージクリアで開きます',
    'needMoreClears': 'このチャプターであと{n}つクリアすると次が開きます',
    'moves': '手数',
    'optimal': '最短',
    'undo': 'もどす',
    'restart': 'やり直し',
    'hint': 'ヒント',
    'next': 'つぎへ',
    'list': '一覧',
    'clear': 'クリア！',
    'nextChapter': '次のチャプター',
    'chapterCleared': 'チャプタークリア！',
    'allCleared': '全チャプタークリア！すごい！',
    'toTitle': 'ホーム',
    'challenge': 'チャレンジ',
    'tutorial1': '画面を押したまま傾けてヒヨコを動かそう！',
    'tutorial1Dpad': '方向ボタンを押してヒヨコを動かそう！',
    'tutorial2': 'タマゴを押して巣に入れてね！',
    'tutorial3': '失敗したら「もどす」を押そう',
    'deadlockHint': 'タマゴが角にはまったよ…もどしてみる？',
    'noHint': '今は道がないみたい…もどそう！',
    'soundOn': '音',
    'joystickHint': 'どこでも押して傾けてね',
    'controlScheme': '操作方法',
    'unlockAll': '全チャプターを開く（確認用）',
    'ctlJoystick': 'スティック — どこでも押して傾ける',
    'ctlDpad': '方向キー — 十字ボタンを押す',
    'resetAll': '記録を全部消す',
    'resetConfirm': '本当に全部消しますか？',
    'cancel': 'キャンセル',
    'ok': 'OK',
    'language': '言語',
    'languageSystem': '端末の言語に合わせる',
    'dailyTitle': '今日のパズル',
    'dailyPlay': '挑戦！',
    'dailyDone': '今日のパズル完了！',
    'streak': '連続記録',
    'day': '日',
    'stickerLocked': '星を集めると開きます',
    'stickerCount': '個',
    'hintsLeft': '残りヒント',
    'hintEmpty': 'ヒントを使い切りました',
    'hintHowTo': '新しいステージをクリアするとヒントが1つ。\n今日のパズルをクリアすると2つもらえます。',
    'hintGot': 'ヒント +{n}',
    'ch1': '草原', 'ch2': '氷の道', 'ch3': 'ひみつの穴', 'ch4': 'ボタンとドア',
    'ch5': 'ひび割れた床', 'ch6': '氷の穴', 'ch7': 'すべる錠前',
    'ch8': 'くだける氷', 'ch9': '穴と錠前', 'ch10': '崩れる通路',
    'ch11': '広い野原', 'ch12': '4つのタマゴの部屋', 'ch13': '凍った広場',
    'ch14': '穴の迷路', 'ch15': '鍵のかかった庭', 'ch16': 'もつれた道',
    'ch17': 'ヒヨコの試練', 'ch18': '5つのタマゴの塔', 'ch19': '最後の関門',
    'ch20': 'ピヨマスター',
    'act1': '第1幕 · まなぶ', 'act2': '第2幕 · まざる',
    'act3': '第3幕 · ひろがる', 'act4': '第4幕 · しれん',
  },
  'zh': {
    'appTitle': 'Peep Push',
    'start': '开始',
    'daily': '每日',
    'stickerBook': '贴纸册',
    'decoBoard': '装饰',
    'settings': '设置',
    'chapterTitle': '章节',
    'lockedChapter': '通关上一章的8个关卡即可解锁',
    'needMoreClears': '本章再通关{n}关即可开启下一章',
    'moves': '步数',
    'optimal': '最少',
    'undo': '撤销',
    'restart': '重来',
    'hint': '提示',
    'next': '下一关',
    'list': '关卡',
    'clear': '通关！',
    'nextChapter': '下一章',
    'chapterCleared': '本章通关！',
    'allCleared': '全部章节通关！太厉害了！',
    'toTitle': '首页',
    'challenge': '挑战',
    'tutorial1': '按住屏幕任意处并倾斜来移动小鸡！',
    'tutorial1Dpad': '按方向键移动小鸡！',
    'tutorial2': '把蛋推进窝里！',
    'tutorial3': '走错了就按撤销',
    'deadlockHint': '蛋卡在角落了…要撤销吗？',
    'noHint': '现在没有通路了…撤销吧！',
    'soundOn': '声音',
    'joystickHint': '按住任意位置并倾斜',
    'controlScheme': '操作方式',
    'unlockAll': '解锁全部章节（测试用）',
    'ctlJoystick': '摇杆 — 按住任意处倾斜',
    'ctlDpad': '方向键 — 点按十字键',
    'resetAll': '清除全部记录',
    'resetConfirm': '确定要清除全部记录吗？',
    'cancel': '取消',
    'ok': '确定',
    'language': '语言',
    'languageSystem': '跟随设备语言',
    'dailyTitle': '今日谜题',
    'dailyPlay': '挑战！',
    'dailyDone': '今日谜题已完成！',
    'streak': '连续天数',
    'day': '天',
    'stickerLocked': '收集星星即可解锁',
    'stickerCount': '个',
    'hintsLeft': '剩余提示',
    'hintEmpty': '提示已用完',
    'hintHowTo': '通关新关卡可获得1个提示。\n完成今日谜题可获得2个。',
    'hintGot': '提示 +{n}',
    'ch1': '草地', 'ch2': '冰路', 'ch3': '秘密洞穴', 'ch4': '按钮与门',
    'ch5': '裂开的地板', 'ch6': '冰洞', 'ch7': '滑动的锁',
    'ch8': '碎裂的冰', 'ch9': '洞穴与锁', 'ch10': '坍塌的通道',
    'ch11': '广阔原野', 'ch12': '四蛋之室', 'ch13': '冰封广场',
    'ch14': '洞穴迷宫', 'ch15': '上锁的花园', 'ch16': '缠绕之路',
    'ch17': '小鸡的试炼', 'ch18': '五蛋之塔', 'ch19': '最终关卡',
    'ch20': '推蛋大师',
    'act1': '第一幕 · 学习', 'act2': '第二幕 · 混合',
    'act3': '第三幕 · 扩展', 'act4': '第四幕 · 试炼',
  },
  'es': {
    'appTitle': 'Peep Push',
    'start': 'Jugar',
    'daily': 'Diario',
    'stickerBook': 'Pegatinas',
    'decoBoard': 'Decorar',
    'settings': 'Ajustes',
    'chapterTitle': 'Capítulo',
    'lockedChapter': 'Completa 8 niveles del capítulo anterior para abrirlo',
    'needMoreClears': 'Completa {n} más en este capítulo para abrir el siguiente',
    'moves': 'Movim.',
    'optimal': 'Mejor',
    'undo': 'Deshacer',
    'restart': 'Reiniciar',
    'hint': 'Pista',
    'next': 'Siguiente',
    'list': 'Niveles',
    'clear': '¡Completado!',
    'nextChapter': 'Siguiente capítulo',
    'chapterCleared': '¡Capítulo completado!',
    'allCleared': '¡Todos los capítulos completados! ¡Increíble!',
    'toTitle': 'Inicio',
    'challenge': 'Reto',
    'tutorial1': '¡Mantén pulsado en cualquier sitio e inclina para mover al pollito!',
    'tutorial1Dpad': '¡Pulsa las flechas para mover al pollito!',
    'tutorial2': '¡Empuja los huevos hasta los nidos!',
    'tutorial3': '¿Te equivocaste? Pulsa deshacer',
    'deadlockHint': 'El huevo está atrapado en una esquina… ¿deshacer?',
    'noHint': 'No hay salida ahora… ¡deshaz!',
    'soundOn': 'Sonido',
    'joystickHint': 'Toca en cualquier sitio e inclina',
    'controlScheme': 'Controles',
    'unlockAll': 'Abrir todos los capítulos (pruebas)',
    'ctlJoystick': 'Joystick — toca donde sea e inclina',
    'ctlDpad': 'Flechas — pulsa la cruceta',
    'resetAll': 'Borrar todo el progreso',
    'resetConfirm': '¿Borrar todo el progreso de verdad?',
    'cancel': 'Cancelar',
    'ok': 'Aceptar',
    'language': 'Idioma',
    'languageSystem': 'Seguir idioma del dispositivo',
    'dailyTitle': 'Puzle de hoy',
    'dailyPlay': '¡Jugar!',
    'dailyDone': '¡Puzle de hoy completado!',
    'streak': 'Racha',
    'day': 'd',
    'stickerLocked': 'Reúne estrellas para abrirlo',
    'stickerCount': '',
    'hintsLeft': 'Pistas',
    'hintEmpty': 'Te has quedado sin pistas',
    'hintHowTo': 'Completa un nivel nuevo y consigue 1 pista.\nEl puzle diario da 2.',
    'hintGot': 'Pista +{n}',
    'ch1': 'Pradera', 'ch2': 'Camino de hielo', 'ch3': 'Madriguera secreta',
    'ch4': 'Botones y puertas', 'ch5': 'Suelo agrietado', 'ch6': 'Madriguera helada',
    'ch7': 'Cerradura resbaladiza', 'ch8': 'Hielo que se rompe',
    'ch9': 'Madriguera y cerradura', 'ch10': 'Pasillo que se hunde',
    'ch11': 'Campo abierto', 'ch12': 'Sala de cuatro huevos',
    'ch13': 'Plaza helada', 'ch14': 'Laberinto de madrigueras',
    'ch15': 'Jardín cerrado', 'ch16': 'Senderos enredados',
    'ch17': 'La prueba del pollito', 'ch18': 'Torre de cinco huevos',
    'ch19': 'Puerta final', 'ch20': 'Maestro Peep',
    'act1': 'Acto 1 · Aprender', 'act2': 'Acto 2 · Mezclar',
    'act3': 'Acto 3 · Ampliar', 'act4': 'Acto 4 · Prueba',
  },
  'fr': {
    'appTitle': 'Peep Push',
    'start': 'Jouer',
    'daily': 'Quotidien',
    'stickerBook': 'Autocollants',
    'decoBoard': 'Décorer',
    'settings': 'Réglages',
    'chapterTitle': 'Chapitre',
    'lockedChapter': 'Termine 8 niveaux du chapitre précédent pour ouvrir',
    'needMoreClears': 'Termine encore {n} niveaux pour ouvrir le chapitre suivant',
    'moves': 'Coups',
    'optimal': 'Idéal',
    'undo': 'Annuler',
    'restart': 'Recommencer',
    'hint': 'Indice',
    'next': 'Suivant',
    'list': 'Niveaux',
    'clear': 'Réussi !',
    'nextChapter': 'Chapitre suivant',
    'chapterCleared': 'Chapitre terminé !',
    'allCleared': 'Tous les chapitres terminés ! Bravo !',
    'toTitle': 'Accueil',
    'challenge': 'Défi',
    'tutorial1': 'Appuie n\'importe où et incline pour déplacer le poussin !',
    'tutorial1Dpad': 'Appuie sur les flèches pour déplacer le poussin !',
    'tutorial2': 'Pousse les œufs dans les nids !',
    'tutorial3': 'Une erreur ? Appuie sur annuler',
    'deadlockHint': 'L\'œuf est coincé dans un coin… annuler ?',
    'noHint': 'Aucun passage pour l\'instant… annule !',
    'soundOn': 'Son',
    'joystickHint': 'Touche n\'importe où et incline',
    'controlScheme': 'Commandes',
    'unlockAll': 'Ouvrir tous les chapitres (test)',
    'ctlJoystick': 'Joystick — touche partout et incline',
    'ctlDpad': 'Flèches — appuie sur la croix',
    'resetAll': 'Effacer toute la progression',
    'resetConfirm': 'Vraiment tout effacer ?',
    'cancel': 'Annuler',
    'ok': 'OK',
    'language': 'Langue',
    'languageSystem': 'Suivre la langue de l\'appareil',
    'dailyTitle': 'Puzzle du jour',
    'dailyPlay': 'Jouer !',
    'dailyDone': 'Puzzle du jour terminé !',
    'streak': 'Série',
    'day': 'j',
    'stickerLocked': 'Collecte des étoiles pour l\'ouvrir',
    'stickerCount': '',
    'hintsLeft': 'Indices',
    'hintEmpty': 'Tu n\'as plus d\'indices',
    'hintHowTo': 'Termine un nouveau niveau pour gagner 1 indice.\nLe puzzle du jour en donne 2.',
    'hintGot': 'Indice +{n}',
    'ch1': 'Prairie', 'ch2': 'Chemin de glace', 'ch3': 'Terrier secret',
    'ch4': 'Boutons et portes', 'ch5': 'Sol fissuré', 'ch6': 'Terrier glacé',
    'ch7': 'Serrure glissante', 'ch8': 'Glace qui casse',
    'ch9': 'Terrier et serrure', 'ch10': 'Couloir qui s\'effondre',
    'ch11': 'Grand pré', 'ch12': 'Salle des quatre œufs',
    'ch13': 'Place gelée', 'ch14': 'Labyrinthe de terriers',
    'ch15': 'Jardin fermé', 'ch16': 'Chemins emmêlés',
    'ch17': 'L\'épreuve du poussin', 'ch18': 'Tour des cinq œufs',
    'ch19': 'Porte finale', 'ch20': 'Maître Peep',
    'act1': 'Acte 1 · Apprendre', 'act2': 'Acte 2 · Mélanger',
    'act3': 'Acte 3 · Élargir', 'act4': 'Acte 4 · Épreuve',
  },
  'de': {
    'appTitle': 'Peep Push',
    'start': 'Spielen',
    'daily': 'Täglich',
    'stickerBook': 'Sticker',
    'decoBoard': 'Gestalten',
    'settings': 'Einstellungen',
    'chapterTitle': 'Kapitel',
    'lockedChapter': 'Schaffe 8 Level im vorigen Kapitel zum Freischalten',
    'needMoreClears': 'Schaffe noch {n} Level, um das nächste Kapitel zu öffnen',
    'moves': 'Züge',
    'optimal': 'Best',
    'undo': 'Zurück',
    'restart': 'Neu',
    'hint': 'Tipp',
    'next': 'Weiter',
    'list': 'Level',
    'clear': 'Geschafft!',
    'nextChapter': 'Nächstes Kapitel',
    'chapterCleared': 'Kapitel geschafft!',
    'allCleared': 'Alle Kapitel geschafft! Klasse!',
    'toTitle': 'Start',
    'challenge': 'Herausforderung',
    'tutorial1': 'Halte irgendwo gedrückt und kippe, um das Küken zu bewegen!',
    'tutorial1Dpad': 'Drücke die Pfeiltasten, um das Küken zu bewegen!',
    'tutorial2': 'Schiebe die Eier in die Nester!',
    'tutorial3': 'Vertan? Tippe auf Zurück',
    'deadlockHint': 'Das Ei steckt in der Ecke fest… zurücknehmen?',
    'noHint': 'Gerade kein Weg… nimm zurück!',
    'soundOn': 'Ton',
    'joystickHint': 'Irgendwo drücken und kippen',
    'controlScheme': 'Steuerung',
    'unlockAll': 'Alle Kapitel öffnen (zum Testen)',
    'ctlJoystick': 'Joystick — überall drücken und kippen',
    'ctlDpad': 'Pfeile — Steuerkreuz tippen',
    'resetAll': 'Fortschritt löschen',
    'resetConfirm': 'Wirklich den ganzen Fortschritt löschen?',
    'cancel': 'Abbrechen',
    'ok': 'OK',
    'language': 'Sprache',
    'languageSystem': 'Gerätesprache verwenden',
    'dailyTitle': 'Rätsel des Tages',
    'dailyPlay': 'Los!',
    'dailyDone': 'Heutiges Rätsel geschafft!',
    'streak': 'Serie',
    'day': 'T',
    'stickerLocked': 'Sammle Sterne zum Freischalten',
    'stickerCount': '',
    'hintsLeft': 'Tipps',
    'hintEmpty': 'Keine Tipps mehr',
    'hintHowTo': 'Ein neues Level bringt 1 Tipp.\nDas Tagesrätsel bringt 2.',
    'hintGot': 'Tipp +{n}',
    'ch1': 'Wiese', 'ch2': 'Eisweg', 'ch3': 'Geheimer Bau',
    'ch4': 'Knöpfe und Türen', 'ch5': 'Rissiger Boden', 'ch6': 'Eisbau',
    'ch7': 'Rutschiges Schloss', 'ch8': 'Brechendes Eis',
    'ch9': 'Bau und Schloss', 'ch10': 'Einstürzender Gang',
    'ch11': 'Weites Feld', 'ch12': 'Kammer der vier Eier',
    'ch13': 'Gefrorener Platz', 'ch14': 'Bau-Labyrinth',
    'ch15': 'Verschlossener Garten', 'ch16': 'Verschlungene Wege',
    'ch17': 'Prüfung des Kükens', 'ch18': 'Turm der fünf Eier',
    'ch19': 'Letztes Tor', 'ch20': 'Peep-Meister',
    'act1': 'Akt 1 · Lernen', 'act2': 'Akt 2 · Mischen',
    'act3': 'Akt 3 · Weiten', 'act4': 'Akt 4 · Prüfung',
  },
  'pt': {
    'appTitle': 'Peep Push',
    'start': 'Jogar',
    'daily': 'Diário',
    'stickerBook': 'Adesivos',
    'decoBoard': 'Decorar',
    'settings': 'Ajustes',
    'chapterTitle': 'Capítulo',
    'lockedChapter': 'Conclua 8 fases do capítulo anterior para abrir',
    'needMoreClears': 'Conclua mais {n} fases para abrir o próximo capítulo',
    'moves': 'Jogadas',
    'optimal': 'Melhor',
    'undo': 'Desfazer',
    'restart': 'Reiniciar',
    'hint': 'Dica',
    'next': 'Próxima',
    'list': 'Fases',
    'clear': 'Concluído!',
    'nextChapter': 'Próximo capítulo',
    'chapterCleared': 'Capítulo concluído!',
    'allCleared': 'Todos os capítulos concluídos! Incrível!',
    'toTitle': 'Início',
    'challenge': 'Desafio',
    'tutorial1': 'Segure em qualquer lugar e incline para mover o pintinho!',
    'tutorial1Dpad': 'Toque nas setas para mover o pintinho!',
    'tutorial2': 'Empurre os ovos para os ninhos!',
    'tutorial3': 'Errou? Toque em desfazer',
    'deadlockHint': 'O ovo ficou preso no canto… desfazer?',
    'noHint': 'Sem caminho agora… desfaça!',
    'soundOn': 'Som',
    'joystickHint': 'Toque em qualquer lugar e incline',
    'controlScheme': 'Controles',
    'unlockAll': 'Abrir todos os capítulos (teste)',
    'ctlJoystick': 'Joystick — toque em qualquer lugar e incline',
    'ctlDpad': 'Setas — toque no direcional',
    'resetAll': 'Apagar todo o progresso',
    'resetConfirm': 'Apagar mesmo todo o progresso?',
    'cancel': 'Cancelar',
    'ok': 'OK',
    'language': 'Idioma',
    'languageSystem': 'Seguir idioma do aparelho',
    'dailyTitle': 'Quebra-cabeça de hoje',
    'dailyPlay': 'Jogar!',
    'dailyDone': 'Quebra-cabeça de hoje concluído!',
    'streak': 'Sequência',
    'day': 'd',
    'stickerLocked': 'Junte estrelas para abrir',
    'stickerCount': '',
    'hintsLeft': 'Dicas',
    'hintEmpty': 'Você ficou sem dicas',
    'hintHowTo': 'Concluir uma fase nova dá 1 dica.\nO quebra-cabeça diário dá 2.',
    'hintGot': 'Dica +{n}',
    'ch1': 'Campina', 'ch2': 'Caminho de gelo', 'ch3': 'Toca secreta',
    'ch4': 'Botões e portas', 'ch5': 'Chão rachado', 'ch6': 'Toca gelada',
    'ch7': 'Fechadura escorregadia', 'ch8': 'Gelo que quebra',
    'ch9': 'Toca e fechadura', 'ch10': 'Corredor que desaba',
    'ch11': 'Campo aberto', 'ch12': 'Sala dos quatro ovos',
    'ch13': 'Praça congelada', 'ch14': 'Labirinto de tocas',
    'ch15': 'Jardim trancado', 'ch16': 'Caminhos emaranhados',
    'ch17': 'Prova do pintinho', 'ch18': 'Torre dos cinco ovos',
    'ch19': 'Portão final', 'ch20': 'Mestre Peep',
    'act1': 'Ato 1 · Aprender', 'act2': 'Ato 2 · Misturar',
    'act3': 'Ato 3 · Ampliar', 'act4': 'Ato 4 · Prova',
  },
  'ru': {
    'appTitle': 'Peep Push',
    'start': 'Играть',
    'daily': 'Ежедневно',
    'stickerBook': 'Наклейки',
    'decoBoard': 'Украсить',
    'settings': 'Настройки',
    'chapterTitle': 'Глава',
    'lockedChapter': 'Пройдите 8 уровней прошлой главы, чтобы открыть',
    'needMoreClears': 'Пройдите ещё {n}, чтобы открыть следующую главу',
    'moves': 'Ходы',
    'optimal': 'Лучший',
    'undo': 'Отмена',
    'restart': 'Заново',
    'hint': 'Подсказка',
    'next': 'Далее',
    'list': 'Уровни',
    'clear': 'Пройдено!',
    'nextChapter': 'Следующая глава',
    'chapterCleared': 'Глава пройдена!',
    'allCleared': 'Все главы пройдены! Отлично!',
    'toTitle': 'В начало',
    'challenge': 'Испытание',
    'tutorial1': 'Нажмите в любом месте и наклоните, чтобы двигать цыплёнка!',
    'tutorial1Dpad': 'Нажимайте стрелки, чтобы двигать цыплёнка!',
    'tutorial2': 'Толкайте яйца в гнёзда!',
    'tutorial3': 'Ошиблись? Нажмите отмену',
    'deadlockHint': 'Яйцо застряло в углу… отменить ход?',
    'noHint': 'Сейчас нет пути… отмените!',
    'soundOn': 'Звук',
    'joystickHint': 'Нажмите где угодно и наклоните',
    'controlScheme': 'Управление',
    'unlockAll': 'Открыть все главы (для проверки)',
    'ctlJoystick': 'Джойстик — нажать где угодно и наклонить',
    'ctlDpad': 'Стрелки — нажимать крестовину',
    'resetAll': 'Стереть весь прогресс',
    'resetConfirm': 'Точно стереть весь прогресс?',
    'cancel': 'Отмена',
    'ok': 'ОК',
    'language': 'Язык',
    'languageSystem': 'Как на устройстве',
    'dailyTitle': 'Головоломка дня',
    'dailyPlay': 'Играть!',
    'dailyDone': 'Головоломка дня пройдена!',
    'streak': 'Серия',
    'day': 'д',
    'stickerLocked': 'Соберите звёзды, чтобы открыть',
    'stickerCount': '',
    'hintsLeft': 'Подсказки',
    'hintEmpty': 'Подсказки закончились',
    'hintHowTo': 'За новый пройденный уровень — 1 подсказка.\nЗа головоломку дня — 2.',
    'hintGot': 'Подсказка +{n}',
    'ch1': 'Луг', 'ch2': 'Ледяная тропа', 'ch3': 'Тайная нора',
    'ch4': 'Кнопки и двери', 'ch5': 'Треснувший пол', 'ch6': 'Ледяная нора',
    'ch7': 'Скользкий замок', 'ch8': 'Ломкий лёд',
    'ch9': 'Нора и замок', 'ch10': 'Рушащийся проход',
    'ch11': 'Широкое поле', 'ch12': 'Зал четырёх яиц',
    'ch13': 'Замёрзшая площадь', 'ch14': 'Лабиринт нор',
    'ch15': 'Запертый сад', 'ch16': 'Запутанные тропы',
    'ch17': 'Испытание цыплёнка', 'ch18': 'Башня пяти яиц',
    'ch19': 'Последние врата', 'ch20': 'Мастер Peep',
    'act1': 'Акт 1 · Учимся', 'act2': 'Акт 2 · Смешиваем',
    'act3': 'Акт 3 · Расширяем', 'act4': 'Акт 4 · Испытание',
  },
  'th': {
    'appTitle': 'Peep Push',
    'start': 'เล่น',
    'daily': 'รายวัน',
    'stickerBook': 'สติกเกอร์',
    'decoBoard': 'ตกแต่ง',
    'settings': 'ตั้งค่า',
    'chapterTitle': 'บท',
    'lockedChapter': 'ผ่าน 8 ด่านในบทก่อนหน้าเพื่อปลดล็อก',
    'needMoreClears': 'ผ่านอีก {n} ด่านเพื่อเปิดบทถัดไป',
    'moves': 'ก้าว',
    'optimal': 'ดีสุด',
    'undo': 'ย้อนกลับ',
    'restart': 'เริ่มใหม่',
    'hint': 'คำใบ้',
    'next': 'ถัดไป',
    'list': 'ด่าน',
    'clear': 'ผ่านแล้ว!',
    'nextChapter': 'บทถัดไป',
    'chapterCleared': 'ผ่านบทนี้แล้ว!',
    'allCleared': 'ผ่านทุกบทแล้ว! เก่งมาก!',
    'toTitle': 'หน้าแรก',
    'challenge': 'ท้าทาย',
    'tutorial1': 'แตะค้างตรงไหนก็ได้แล้วเอียงเพื่อขยับลูกเจี๊ยบ!',
    'tutorial1Dpad': 'กดปุ่มลูกศรเพื่อขยับลูกเจี๊ยบ!',
    'tutorial2': 'ดันไข่เข้ารัง!',
    'tutorial3': 'พลาดแล้วเหรอ? กดย้อนกลับ',
    'deadlockHint': 'ไข่ติดมุมแล้ว… ย้อนกลับไหม?',
    'noHint': 'ตอนนี้ไม่มีทางไป… ย้อนกลับเลย!',
    'soundOn': 'เสียง',
    'joystickHint': 'แตะตรงไหนก็ได้แล้วเอียง',
    'controlScheme': 'การควบคุม',
    'unlockAll': 'เปิดทุกบท (สำหรับทดสอบ)',
    'ctlJoystick': 'จอยสติ๊ก — แตะตรงไหนก็ได้แล้วเอียง',
    'ctlDpad': 'ลูกศร — กดปุ่มทิศทาง',
    'resetAll': 'ลบความคืบหน้าทั้งหมด',
    'resetConfirm': 'ลบความคืบหน้าทั้งหมดจริงหรือ?',
    'cancel': 'ยกเลิก',
    'ok': 'ตกลง',
    'language': 'ภาษา',
    'languageSystem': 'ตามภาษาเครื่อง',
    'dailyTitle': 'ปริศนาวันนี้',
    'dailyPlay': 'ลุย!',
    'dailyDone': 'ผ่านปริศนาวันนี้แล้ว!',
    'streak': 'ต่อเนื่อง',
    'day': 'วัน',
    'stickerLocked': 'สะสมดาวเพื่อปลดล็อก',
    'stickerCount': '',
    'hintsLeft': 'คำใบ้',
    'hintEmpty': 'คำใบ้หมดแล้ว',
    'hintHowTo': 'ผ่านด่านใหม่ได้คำใบ้ 1 อัน\nผ่านปริศนาวันนี้ได้ 2 อัน',
    'hintGot': 'คำใบ้ +{n}',
    'ch1': 'ทุ่งหญ้า', 'ch2': 'ทางน้ำแข็ง', 'ch3': 'โพรงลับ',
    'ch4': 'ปุ่มกับประตู', 'ch5': 'พื้นแตกร้าว', 'ch6': 'โพรงน้ำแข็ง',
    'ch7': 'กลอนลื่น', 'ch8': 'น้ำแข็งแตก',
    'ch9': 'โพรงกับกลอน', 'ch10': 'ทางเดินถล่ม',
    'ch11': 'ทุ่งกว้าง', 'ch12': 'ห้องสี่ไข่',
    'ch13': 'ลานน้ำแข็ง', 'ch14': 'เขาวงกตโพรง',
    'ch15': 'สวนที่ถูกล็อก', 'ch16': 'ทางพันกัน',
    'ch17': 'บททดสอบลูกเจี๊ยบ', 'ch18': 'หอคอยห้าไข่',
    'ch19': 'ประตูสุดท้าย', 'ch20': 'ยอดฝีมือ Peep',
    'act1': 'องก์ 1 · เรียนรู้', 'act2': 'องก์ 2 · ผสม',
    'act3': 'องก์ 3 · ขยาย', 'act4': 'องก์ 4 · ทดสอบ',
  },
  'vi': {
    'appTitle': 'Peep Push',
    'start': 'Chơi',
    'daily': 'Hằng ngày',
    'stickerBook': 'Nhãn dán',
    'decoBoard': 'Trang trí',
    'settings': 'Cài đặt',
    'chapterTitle': 'Chương',
    'lockedChapter': 'Qua 8 màn ở chương trước để mở khóa',
    'needMoreClears': 'Qua thêm {n} màn để mở chương tiếp theo',
    'moves': 'Lượt',
    'optimal': 'Tốt nhất',
    'undo': 'Hoàn tác',
    'restart': 'Chơi lại',
    'hint': 'Gợi ý',
    'next': 'Tiếp',
    'list': 'Màn chơi',
    'clear': 'Hoàn thành!',
    'nextChapter': 'Chương tiếp theo',
    'chapterCleared': 'Xong chương!',
    'allCleared': 'Đã qua hết các chương! Tuyệt vời!',
    'toTitle': 'Trang chính',
    'challenge': 'Thử thách',
    'tutorial1': 'Giữ bất kỳ đâu rồi nghiêng để di chuyển gà con!',
    'tutorial1Dpad': 'Nhấn các nút mũi tên để di chuyển gà con!',
    'tutorial2': 'Đẩy trứng vào tổ nhé!',
    'tutorial3': 'Lỡ sai? Nhấn hoàn tác',
    'deadlockHint': 'Trứng kẹt ở góc rồi… hoàn tác nhé?',
    'noHint': 'Giờ không còn đường… hoàn tác đi!',
    'soundOn': 'Âm thanh',
    'joystickHint': 'Chạm bất kỳ đâu rồi nghiêng',
    'controlScheme': 'Điều khiển',
    'unlockAll': 'Mở tất cả chương (để kiểm tra)',
    'ctlJoystick': 'Cần điều khiển — chạm bất kỳ đâu rồi nghiêng',
    'ctlDpad': 'Mũi tên — nhấn phím định hướng',
    'resetAll': 'Xóa toàn bộ tiến trình',
    'resetConfirm': 'Xóa toàn bộ tiến trình thật chứ?',
    'cancel': 'Hủy',
    'ok': 'OK',
    'language': 'Ngôn ngữ',
    'languageSystem': 'Theo ngôn ngữ máy',
    'dailyTitle': 'Câu đố hôm nay',
    'dailyPlay': 'Chơi!',
    'dailyDone': 'Đã xong câu đố hôm nay!',
    'streak': 'Chuỗi ngày',
    'day': 'ngày',
    'stickerLocked': 'Thu thập sao để mở khóa',
    'stickerCount': '',
    'hintsLeft': 'Gợi ý',
    'hintEmpty': 'Bạn đã hết gợi ý',
    'hintHowTo': 'Qua một màn mới được 1 gợi ý.\nCâu đố hằng ngày được 2.',
    'hintGot': 'Gợi ý +{n}',
    'ch1': 'Đồng cỏ', 'ch2': 'Đường băng', 'ch3': 'Hang bí mật',
    'ch4': 'Nút và cửa', 'ch5': 'Sàn nứt', 'ch6': 'Hang băng',
    'ch7': 'Ổ khóa trơn', 'ch8': 'Băng vỡ',
    'ch9': 'Hang và ổ khóa', 'ch10': 'Lối đi sụp',
    'ch11': 'Cánh đồng rộng', 'ch12': 'Phòng bốn trứng',
    'ch13': 'Quảng trường băng', 'ch14': 'Mê cung hang',
    'ch15': 'Khu vườn khóa kín', 'ch16': 'Lối đi rối',
    'ch17': 'Thử thách gà con', 'ch18': 'Tháp năm trứng',
    'ch19': 'Cổng cuối', 'ch20': 'Cao thủ Peep',
    'act1': 'Hồi 1 · Học', 'act2': 'Hồi 2 · Pha trộn',
    'act3': 'Hồi 3 · Mở rộng', 'act4': 'Hồi 4 · Thử thách',
  },
  'id': {
    'appTitle': 'Peep Push',
    'start': 'Main',
    'daily': 'Harian',
    'stickerBook': 'Stiker',
    'decoBoard': 'Hias',
    'settings': 'Pengaturan',
    'chapterTitle': 'Bab',
    'lockedChapter': 'Selesaikan 8 level di bab sebelumnya untuk membuka',
    'needMoreClears': 'Selesaikan {n} level lagi untuk membuka bab berikutnya',
    'moves': 'Langkah',
    'optimal': 'Terbaik',
    'undo': 'Batal',
    'restart': 'Ulangi',
    'hint': 'Petunjuk',
    'next': 'Lanjut',
    'list': 'Level',
    'clear': 'Selesai!',
    'nextChapter': 'Bab berikutnya',
    'chapterCleared': 'Bab selesai!',
    'allCleared': 'Semua bab selesai! Hebat!',
    'toTitle': 'Beranda',
    'challenge': 'Tantangan',
    'tutorial1': 'Tahan di mana saja lalu miringkan untuk menggerakkan anak ayam!',
    'tutorial1Dpad': 'Tekan tombol panah untuk menggerakkan anak ayam!',
    'tutorial2': 'Dorong telur ke sarangnya!',
    'tutorial3': 'Salah langkah? Tekan batal',
    'deadlockHint': 'Telurnya tersangkut di sudut… batalkan?',
    'noHint': 'Tidak ada jalan sekarang… batalkan!',
    'soundOn': 'Suara',
    'joystickHint': 'Sentuh di mana saja lalu miringkan',
    'controlScheme': 'Kontrol',
    'unlockAll': 'Buka semua bab (untuk pengujian)',
    'ctlJoystick': 'Joystick — sentuh di mana saja lalu miringkan',
    'ctlDpad': 'Panah — tekan tombol arah',
    'resetAll': 'Hapus semua kemajuan',
    'resetConfirm': 'Yakin hapus semua kemajuan?',
    'cancel': 'Batal',
    'ok': 'OK',
    'language': 'Bahasa',
    'languageSystem': 'Ikuti bahasa perangkat',
    'dailyTitle': 'Teka-teki hari ini',
    'dailyPlay': 'Main!',
    'dailyDone': 'Teka-teki hari ini selesai!',
    'streak': 'Beruntun',
    'day': 'h',
    'stickerLocked': 'Kumpulkan bintang untuk membuka',
    'stickerCount': '',
    'hintsLeft': 'Petunjuk',
    'hintEmpty': 'Petunjukmu habis',
    'hintHowTo': 'Selesaikan level baru dapat 1 petunjuk.\nTeka-teki harian dapat 2.',
    'hintGot': 'Petunjuk +{n}',
    'ch1': 'Padang Rumput', 'ch2': 'Jalur Es', 'ch3': 'Liang Rahasia',
    'ch4': 'Tombol dan Pintu', 'ch5': 'Lantai Retak', 'ch6': 'Liang Es',
    'ch7': 'Kunci Licin', 'ch8': 'Es yang Pecah',
    'ch9': 'Liang dan Kunci', 'ch10': 'Lorong Runtuh',
    'ch11': 'Padang Luas', 'ch12': 'Ruang Empat Telur',
    'ch13': 'Alun-alun Beku', 'ch14': 'Labirin Liang',
    'ch15': 'Taman Terkunci', 'ch16': 'Jalan Berbelit',
    'ch17': 'Ujian Anak Ayam', 'ch18': 'Menara Lima Telur',
    'ch19': 'Gerbang Terakhir', 'ch20': 'Master Peep',
    'act1': 'Babak 1 · Belajar', 'act2': 'Babak 2 · Campur',
    'act3': 'Babak 3 · Meluas', 'act4': 'Babak 4 · Ujian',
  },
};
